name: Lint
on:
  push:
    branches:
      - "**"

jobs:
  lint:
    uses: ./.github/workflows/node-workflow.yml
    with:
      use-matrix: true
      run-command: pnpm run lint
      command-description: Lint
