name: NPM Update Reminder

on:
  schedule:
    # Runs on April 1st and October 1st 9:00 AM UTC each year
    - cron: '0 9 1 4,10 *'

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔄 Time to update npm dependencies',
              body: 'This is an automated reminder to check and update npm packages for security and feature improvements.'
            })
