name: Package Update Reminder

on:
  schedule:
    # Runs monthly on the 15th at 3:55 AM UTC each year (3:55 to avoid high-load times)
    # Doesn't create an issue unless its April or October, but monthly pinging is required to keep workflow alive
    - cron: '55 3 15 * *'
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check month
        id: check-month
        run: |
          # Get current month (1-12) as an integer
          MONTH=$(date +%m)
          MONTH=$((10#$MONTH))
          
          # Exit workflow if not April (4) or October (10)
          if [[ $MONTH -ne 4 && $MONTH -ne 11 ]]; then
            echo "Not April or October, exiting workflow early"
            exit 0
          fi
          
          echo "It's April or October, continuing with issue creation"

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check outdated packages
        id: outdated
        run: |
          # Create a file to store the output
          OUTDATED_FILE="outdated_packages.txt"
          
          # Run pnpm outdated and save output to file, don't fail if no outdated packages
          pnpm outdated > $OUTDATED_FILE || true
          
          # Read the file content and format it for GitHub Actions output
          OUTDATED_CONTENT=$(cat $OUTDATED_FILE)
          
          # Use delimiter to safely pass multiline content
          echo "OUTDATED_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$OUTDATED_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Issue
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const outdatedContent = process.env.OUTDATED_CONTENT || "No outdated packages found";

            // Create a formatted body with Markdown
            const issueBody = `# Bi-annual dependency update

            This is an automated reminder to check and update packages for security and feature improvements.

            ## Outdated NPM Packages

            \`\`\`
            ${outdatedContent}
            \`\`\`

            ## Checklist:
            - [ ] Review and update outdated npm packages
            - [ ] Review and update workflow actions
            - [ ] Update Node.js versions in workflows
            - [ ] Bump pnpm version`;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔄 Reminder: Update dependencies',
              body: issueBody
            });
