name: CI
on:
  push:
    branches:
      - "**"

jobs:
  test:
    uses: ./.github/workflows/node-workflow.yml
    with:
      use-matrix: true
      run-command: pnpm run test
      command-description: Test
